//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalManagementEntities : DbContext
    {
        public HospitalManagementEntities()
            : base("name=HospitalManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergy> Allergy { get; set; }
        public virtual DbSet<Center> Center { get; set; }
        public virtual DbSet<Diagnostics> Diagnostics { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Patient_Case> Patient_Case { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Problems> Problems { get; set; }
    }
}
