//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Patient_Case = new HashSet<Patient_Case>();
        }
    
        public long CR_Number { get; set; }
        public Nullable<long> Aadhar_No { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Relative { get; set; }
        public string Relative_Name { get; set; }
        public Nullable<int> Age_Year { get; set; }
        public Nullable<int> Age_Month { get; set; }
        public string Blood_Group { get; set; }
        public string Marital_Status { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Email { get; set; }
        public string Picture { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<int> District_Name { get; set; }
        public Nullable<int> Place { get; set; }
        public Nullable<long> PIN { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public Nullable<bool> Admin { get; set; }
    
        public virtual District District { get; set; }
        public virtual Place Place1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Case> Patient_Case { get; set; }
    }
}
