//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Case
    {
        public long Case_No { get; set; }
        public Nullable<long> Patient_ID { get; set; }
        public string Gender { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Medical_Records { get; set; }
        public string Exam_Category { get; set; }
        public string Examination_def { get; set; }
        public Nullable<int> Allergy_Name { get; set; }
        public string Allergy_Status { get; set; }
        public string Allergy_Duration { get; set; }
        public string Allergy_Severity { get; set; }
        public string Allergy_Def { get; set; }
        public Nullable<int> Problem_Name { get; set; }
        public string Problem_Defination { get; set; }
        public Nullable<int> Diagnostics_Name { get; set; }
        public Nullable<int> District_Name { get; set; }
        public Nullable<int> Place { get; set; }
        public Nullable<int> Center_Name { get; set; }
        public Nullable<int> Doctor_Name { get; set; }
    
        public virtual Allergy Allergy { get; set; }
        public virtual Center Center { get; set; }
        public virtual Diagnostics Diagnostics { get; set; }
        public virtual District District { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Place Place1 { get; set; }
        public virtual Problems Problems { get; set; }
    }
}
